name: Compilation_Test
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo files
        uses: actions/checkout@v4.2.2
      - name: Compile files
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: Modular_document
          root_file: Modular_document.tex
      - name: Upload compiled file
        uses: actions/upload-artifact@v4
        with: 
          name: Modular_document
          path: Modular_document/Modular_document.pdf
